name: Build the Docker image and push to the Docker Hub

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      APP_PORT: 3000
      APP_CONTAINER: chat-app
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
      - name: Build the image
        run: |
          docker build -t awesomelike/$REPO_NAME:${{ github.sha }} .
      
      - name: Push the image to the registry
        run: |
          docker push awesomelike/$REPO_NAME:${{ github.sha }}
      
      - name: Deploy the app
        uses: appleboy/ssh-action@v0.1.2
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: APP_PORT,REPO_NAME,APP_CONTAINER
          script: |
            sleep 10s;
            docker rm -f $APP_CONTAINER
            (docker rmi $(docker images | grep '$APP_CONTAINER')) || true
            docker run --name $APP_CONTAINER -p $APP_PORT:3000 -d --restart unless-stopped awesomelike/$REPO_NAME:${{ github.sha }}
  
  